include:
  - backend/docker-compose.yml

services:
  frontend:
    build: ./frontend
    command: pnpm dev --hostname 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/next.config.mjs:/app/next.config.mjs
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/tsconfig.json:/app/tsconfig.json
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000/api
      NODE_ENV: development
