from typing import Protocol
from uuid import UUID

from src.db.models.account import Account


class AccountRepository(Protocol):
    async def add(self, account: Account) -> None: ...

    async def get_by_id(self, account_id: UUID) -> Account | None: ...

    async def list_by_user(self, user_id: UUID) -> list[Account]: ...

    async def list_all(self) -> list[Account]: ...

    async def delete(self, account_id: UUID) -> None: ...

    async def update(self, account: Account) -> None: ...
